name: Build LaTeX document

on: 
  push:
    branches:
      - main

jobs:
  build-latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@main
        with:
          root_file: main.tex
      - name: Organize output
        run: | 
          mkdir output
          ls
          mv main.pdf output/manuscript.pdf
      - name: Upload output as artifact
        uses: actions/upload-artifact@master
        with: 
          name: manuscript.pdf
          path: output/manuscript.pdf
      
